apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ${{ values.name }}-on-pull-request
  namespace: ${{ values.namespace }}
  labels:
    argocd/app-name: ${{ values.name }}
    janus-idp.io/tekton: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }} 
    app.kubernetes.io/part-of: ${{ values.name }}
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/redhat-appstudio/tssc-sample-pipelines/main/new-for-dance/pipelines-helm/pipeline-promote.yaml"
    # Todo: pac tasks need to be added after the pipleline has been finalized
    # pipelinesascode.tekton.dev/task-0: "https://raw.githubusercontent.com/redhat-appstudio/tssc-sample-pipelines/main/pac/tasks/init.yaml"
    # pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/redhat-appstudio/tssc-sample-pipelines/main/pac/tasks/git-clone.yaml"
    # pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/redhat-appstudio/tssc-sample-pipelines/main/new-for-dance/tasks/task-verify-enterprise-contract.yaml"
spec: 
  params:
  # Todo: params need to be updated after the pipeline has been finalized
  - name: namespace
    value: ${{ values.namespace }}
  - name: gitops-repo-url
    value: ${{ values.repoURL }}
  - name: source-repo-url
    value: ${{ values.srcRepoURL }}
  - name: component-id
    value: ${{ values.name }}
  - name: revision
    value: '{{revision}}'
  - name: argocd-host
    value: argocd.example.com # hardcoded for now
  pipelineRef:
    name: ${{ values.appName }}-promote
  workspaces:
    - name: workspace
      volumeClaimTemplate: 
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
 
