apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ${{ values.appName }}-repository
spec:
  url: ${{ values.repoURL }}
  secret:
      name: "gitops-auth-secret"
      # Set this if you have a different key in your secret
      key: "password"
  webhook_secret:
      name: "rhtap-pipeline-secret"
      # Set this if you have a different key in your secret
      key: "webhook-github-secret"