apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }} 
  description: ${{ values.description}}   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=${{  values.name  }}  
    janus-idp.io/tekton: ${{ values.name }} 
    backstage.io/kubernetes-id: ${{ values.name }} 
    backstage.io/techdocs-ref: dir:. 
  tags: ${{ values.tags }} 
spec:
  type: service
  owner: ${{ values.owner }} 
  lifecycle: experimental
 